### ISSUE TITLE
Color the algolia search bar into the Sherlock theme

### ISSUE THREAD

**Issue by nsunami** [PostReview/postreview-app#242]
Currently, we have the default autocomplete theme for the Algolia search bar. 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/17035406/184517877-d91b73a0-a813-41a7-a6e7-c74596a01192.png">

<img width="463" alt="image" src="https://user-images.githubusercontent.com/17035406/184517883-8283eee7-a39f-4fd5-a637-01a732f8be5b.png">

<img width="392" alt="image" src="https://user-images.githubusercontent.com/17035406/184517900-10c565f1-b519-4f78-8833-250febbed72c.png">
<img width="383" alt="image" src="https://user-images.githubusercontent.com/17035406/184517902-0f53ef3d-ef46-4041-b2da-aff39232f7b4.png">

**Comment by nsunami** [comment]
We can use the process described here: https://github.com/libscie/ResearchEquals.com/pull/156

In essence:

1. Copy and internalize the algolia.css 
2. Edit the CSS directly

**Comment by jazellemaira** [comment]
Let's change the highlight color for the words when it matches the input. The yellow is painful to look at. Make it gray-medium?

Also, let's make the description highlight background color for the hovered results. Make it the same color for light and dark modes. Right now only the dark mode is highlighted green. 

![Screen Shot 2022-08-17 at 2 41 36 PM](https://user-images.githubusercontent.com/42837484/185218722-b1a241f6-725f-4950-89b9-dcf99452bb16.png)
![Screen Shot 2022-08-17 at 2 41 59 PM](https://user-images.githubusercontent.com/42837484/185218724-cb648926-1980-4857-8b7f-4fa219a143a8.png)
.
