### ISSUE TITLE
Add Cookies confirmation dialog

### ISSUE THREAD

**Issue by nsunami** [PostReview/postreview-app#335]
Currently, there is no dialog for accepting or declining cookies. Add a dialog.

**Comment by nsunami** [comment]
@jazellemaira We may need a design for this 🙏 🥺

**Comment by jazellemaira** [comment]
@nsunami 

We already have a design for this 😉 

![image](https://user-images.githubusercontent.com/42837484/187053668-6dad39e7-ae29-4bfc-b7fe-c0ad43212143.png)
![image](https://user-images.githubusercontent.com/42837484/187053673-e3cadaa1-952c-4b0d-bbbd-27896bc26f0b.png)

**Comment by jazellemaira** [comment]
It becomes a pop-up on mobile because the message is too long to be a snack bar.
