### ISSUE TITLE
[Bug]: Double-clicking a rating star causes 400 error when the user has no review

### ISSUE THREAD

**Issue by antonlebed** [PostReview/postreview-app#85]
### URL of the Page

https://postreview-app.herokuapp.com/articles/2fe810b8-9d30-42a3-9c3e-682e3213e7e8

### What happened?

![image](https://user-images.githubusercontent.com/73071333/151015357-98453b5f-32e1-44c8-a4a4-2864b1010a73.png)
Only works for two papers:
1) Recent Sexual Assault and Suicidal Behaviors in College Students: The Moderating Role of Anger
2) Does the Prospect of Fulfilling Belonging Affect Social Responses to Rejection? A Conceptual Replication Attempt

Somehow is **not** the issue for this paper - Verified, Shared, Modular, and Provenance Based Research Communication with the Dat Protocol
However, the same error can be caused by clicking more than once on the stars while editing "Verified, Shared, Modular, and Provenance Based Research Communication with the Dat Protocol" ONLY if you click on Findings, Interpretation, and Significance (but works fine for Research Question and Design for some reason).

### Steps to reproduce

1. initiate the rating pop up
2. click on ANY of the stars 
3. click the SECOND time on any of the stars (even the same star) produces 400 error 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coglebed** [comment]
this issue sometimes can occur when editing the "Verified, Shared, Modular, and Provenance Based Research Communication with the Dat Protocol" paper, but it's much harder to replicate

**Comment by coglebed** [comment]
Ah, I figured it out - the same error can be caused by clicking more than once on the stars while editing "Verified, Shared, Modular, and Provenance Based Research Communication with the Dat Protocol" ONLY if you click on Findings, Interpretation, and Significance (but works fine for Research Question and Design for some reason).
